name: 🚀 Documentation Feature Request
description: Suggest an idea for this project
title: "[Feature]: "
labels: ["type: feature"]
body:
    - type: markdown
      attributes:
          value: |
              Thanks for taking the time to fill out this feature request!
              Before you create the issue:
              * Search the existing issues first, as yours may be a duplicate.
    - type: textarea
      id: documentation-feature-request
      attributes:
          label: Describe your feature request for the documentation
          description: A clear and concise description of what would you like to see being added.
      validations:
          required: true
    - type: textarea
      id: alternatives
      attributes:
          label: Describe possible alternatives
          description: A clear and concise description of any alternative solutions or features you've considered.
    - type: textarea
      id: additional-context
      attributes:
          label: Additional Context
          description: Add any other context about the feature request here.
